SIM_COUNT = 10
EPOCHS = 50
TIMEOUT = 200
TRAIN_MAX_MIN_DURATION = 30

SHOW_FIRST = True
SHOW_EVERY = 100
RENDER_DELAY = 0.0003

REPLAY_MEMORY_SIZE = 5 * 200 * SIM_COUNT  # 10 full games 3k each
MIN_BATCH_SIZE = 10
MAX_BATCH_SIZE = 1000

# Training method
ALLOW_TRAIN = True
LOAD_MODEL = True
STEP_TRAINING = True

model = "StepModel" if STEP_TRAINING else "EpochModel"
MODEL_NAME = f"{model}-5--MB_{MIN_BATCH_SIZE}"

DENSE1 = 32
DENSE2 = 16
# Training params
DISCOUNT = 0.9
AGENT_LR = 1e-4
FIRST_EPS = 0.3
RAMP_EPS = 0.3
INITIAL_SMALL_EPS = 0.05
END_EPS = 0
EPS_INTERVAL = 30

# Settings
SAVE_PICS = ALLOW_TRAIN
SHOW_LAST = False
# PLOT_ALL_QS = True
# PLOT_FIRST_QS = False
# COMBINE_QS = True
SOUND_ALERT = True
