SIM_COUNT = 5
EPOCHS = 500
TIMEOUT = 200
TRAIN_MAX_MIN_DURATION = 10

SHOW_FIRST = True
SHOW_EVERY = 50
RENDER_DELAY = 0.0003

REPLAY_MEMORY_SIZE = 5 * 200 * SIM_COUNT  # 10 full games 3k each
MIN_BATCH_SIZE = 10
MAX_BATCH_SIZE = 1000

# Training method
ALLOW_TRAIN = True
LOAD_MODEL = True

model = "StepModel"
MODEL_NAME = f"Continous-{model}-10--MB_{MIN_BATCH_SIZE}"

DENSE1 = 512
DENSE2 = 512
# Training params
AGENT_LR = 1e-4

DISCOUNT = 0.95
FIRST_EPS = 0.3
RAMP_EPS = 0.2
INITIAL_SMALL_EPS = 0.05
END_EPS = 0
EPS_INTERVAL = 50

# Settings
SAVE_PICS = ALLOW_TRAIN
SHOW_LAST = False
# PLOT_ALL_QS = True
# PLOT_FIRST_QS = False
# COMBINE_QS = True
SOUND_ALERT = True
