SIM_COUNT = 1
EPOCHS = 200
TRAIN_MAX_MIN_DURATION = 10
TIMEOUT_AGENT = 30  # seconds

SHOW_FIRST = True
SHOW_INTERVAL = 1  # in minutes
RENDER_DELAY = 0.0003
RENDER_WITH_ZERO_EPS = True

REPLAY_MEMORY_SIZE = 100_000 * SIM_COUNT
MIN_BATCH_SIZE = 1
MAX_BATCH_SIZE = 1
CLEAR_MEMORY_AFTER_TRAIN = True

# Training method
ALLOW_TRAIN = True
LOAD_MODEL = True
SAVE_MODEL = True

MODEL_NAME = f"Model2-positive-loss"

DENSE1 = 250
DENSE2 = 250
DROPOUT1 = 0.1
DROPOUT2 = 0.2

# Training params
ALPHA = 1e-4
BETA = 1e-3
GAMMA = 0.95

ENABLE_EPS = False
FIRST_EPS = 0.3
RAMP_EPS = 0.4
INITIAL_SMALL_EPS = 0.03
END_EPS = 0
EPS_INTERVAL = 20

# Settings
SAVE_PICS = ALLOW_TRAIN
SHOW_LAST = False
SOUND_ALERT = True
# PLOT_ALL_QS = True
# PLOT_FIRST_QS = False
# COMBINE_QS = True


ACTION_SPACE = 4  # Turn left, right or none
INPUT_SHAPE = (8,)
