SIM_COUNT = 5
EPOCHS = 100
TRAIN_MAX_MIN_DURATION = 10
TIMEOUT_AGENT = 60  # seconds

SHOW_FIRST = True
SHOW_INTERVAL = 5  # in minutes
RENDER_DELAY = 0.0003
RENDER_WITH_ZERO_EPS = True

REPLAY_MEMORY_SIZE = 100_000 * SIM_COUNT
MIN_BATCH_SIZE = 1
MAX_BATCH_SIZE = SIM_COUNT
CLEAR_MEMORY_AFTER_TRAIN = True

# Training method
ALLOW_TRAIN = True
LOAD_MODEL = True
SAVE_MODEL = True

MODEL_NAME = f"Model-14-a>=b"

DENSE1 = 1000
DENSE2 = 1000
DROPOUT1 = 0.1
DROPOUT2 = 0.2

# Training params
ALPHA = 3e-5
BETA = 1e-5
GAMMA = 0.95

ENABLE_EPS = False
FIRST_EPS = 0.3
RAMP_EPS = 0.4
INITIAL_SMALL_EPS = 0.03
END_EPS = 0
EPS_INTERVAL = 20

# Settings
SAVE_PICS = ALLOW_TRAIN
SHOW_LAST = False
SOUND_ALERT = True
# PLOT_ALL_QS = True
# PLOT_FIRST_QS = False
# COMBINE_QS = True


ACTION_SPACE = 4  # Turn left, right or none
INPUT_SHAPE = (8,)
